all : p1 p2 p3 p4 p5 p6 p7 p8

clean:
	rm -f p1 p2 p3 p4 p5 p6 p7 p8

p1: p1.c
	gcc -g -Wall -o p1 p1.c

p2: p2.c
	gcc -g -Wall -o p2 p2.c

p3: p3.c
	gcc -g -Wall -o p3 p3.c

p4: p4.c
	gcc -g -Wall -o p4 p4.c

p5: p5.c
	gcc -g -Wall -o p5 p5.c

p6: p6.c
	gcc -g -Wall -o p6 p6.c

p7 : p7.c
	gcc -g -Wall -o p7 p7.c

p8: p8.c
	gcc -g -Wall -o p8 p8.c